baseURL = "https://hogcrankerz.com/"
theme = "PaperMod"

# Generate real HTML pages (plus RSS and sitemap) for all sections
[outputs]
home    = ["HTML", "RSS", "SITEMAP"]
section = ["HTML", "RSS"]
taxonomy = ["HTML", "RSS"]
term     = ["HTML", "RSS"]

# If you had disableKinds before, make sure "home" and "page" are NOT disabled.
# Example (safe):
# disableKinds = ["taxonomy", "term"]  # <-- do NOT include "home" or "page"
